# config/application.yml
defaults: &defaults
  urls:
    search:
      address: http://search.ezags.at-consulting.ru/addresses/document/_search
      names: http://search.ezags.at-consulting.ru

  ezags:
    url: 'http://192.168.157.183:8080'
    service:
      order: 'http://localhost:8080'


development:
  <<: *defaults

develop:
  <<: *defaults
  ezags:
    service:
      order: '/InterDepPersonalService/InterDepPersonalServiceImpl'

staging:
  <<: *defaults
