# config/application.yml
defaults: &defaults
  urls:
    search:
      address: http://search.ezags.at-consulting.ru/addresses/document/_search
      names: http://search.ezags.at-consulting.ru

  services:
    enquiry:
      endpoint: http://search.ezags.at-consulting.ru
    retro:
      endpoint: http://retro-stage.ezags.at-consulting.ru

  ezags:
    url: 'http://192.168.157.183:8080'
    service:
      order: 'http://localhost:8080'

  rzags:
    url: 'http://localhost:3000'

development:
  <<: *defaults

develop:
  <<: *defaults
  ezags:
    url: 'http://192.168.157.183:8080'
    service:
      order: '/InterDepPersonalService/InterDepPersonalServiceImpl'
  rzags:
    url: 'http://rzags-test.ezags.at-consulting.ru'

staging:
  <<: *defaults
  ezags:
    url: 'http://192.168.100.165:8080'
    service:
      order: '/InterDepPersonalService/InterDepPersonalServiceImpl'
  rzags:
    url: 'http://rzags-uat.ezags.at-consulting.ru'

